-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
INNER JOIN (SELECT *
            FROM ANIMAL_OUTS
            WHERE SEX_UPON_OUTCOME NOT LIKE "Intact%") AS S
    ON I.ANIMAL_ID = S.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE "Intact%";
            