-- 코드를 입력하세요
SET @HOUR_COUNT := -1;

SELECT @HOUR_COUNT :=@HOUR_COUNT + 1 AS HOUR,
IFNULL((SELECT COUNT(DATETIME)
      FROM ANIMAL_OUTS
      WHERE @HOUR_COUNT = HOUR(DATETIME)
      GROUP BY HOUR(DATETIME)
      ), 0) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR_COUNT < 23
UNION
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS "COUNT"
FROM ANIMAL_OUTS
WHERE DATETIME 
    BETWEEN DATE_FORMAT(NOW(), "%Y-%m%d 00:00:00:")
                        AND DATE_FORMAT(NOW(), "%Y-%m%d 23:59:59:")
GROUP BY HOUR
ORDER BY HOUR;
