-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, 
    SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK 
INNER JOIN BOOK_SALES
    USING (BOOK_ID)
INNER JOIN AUTHOR
    USING (AUTHOR_ID)
WHERE 
    YEAR(SALES_DATE) = "2022" AND
    MONTH(SALES_DATE) = "01"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC;




    
    
