-- 코드를 입력하세요
SELECT R.HISTORY_ID, 
CASE
    WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 < 7
        THEN ROUND((DATEDIFF(R.END_DATE, R.START_DATE) + 1) * C.DAILY_FEE * 1)
    WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 < 30
        THEN ROUND((DATEDIFF(R.END_DATE, R.START_DATE) + 1) * C.DAILY_FEE * 0.95)
    WHEN DATEDIFF(R.END_DATE, R.START_DATE) + 1 < 90
        THEN ROUND((DATEDIFF(R.END_DATE, R.START_DATE) + 1) * C.DAILY_FEE * 0.92)
    ELSE ROUND((DATEDIFF(R.END_DATE, R.START_DATE) + 1) * C.DAILY_FEE * 0.85)
END AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
    ON C.CAR_ID = R.CAR_ID
INNER JOIN (SELECT *
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
            WHERE CAR_TYPE = "트럭") AS T
        ON C.CAR_TYPE = T.CAR_TYPE
GROUP BY R.HISTORY_ID
ORDER BY FEE DESC,
    R.HISTORY_ID DESC;
        
# SELECT B.HISTORY_ID, ROUND((DATEDIFF(B.END_DATE, B.START_DATE)+1) * A.DAILY_FEE * (
#     CASE
#         WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 7 THEN 1
#         WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 30 THEN 0.95
#         WHEN DATEDIFF(B.END_DATE, B.START_DATE)+1 < 90 THEN 0.92
#         ELSE 0.85
#     END
# )) as FEE
# FROM CAR_RENTAL_COMPANY_CAR A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE = '트럭'
# GROUP BY HISTORY_ID
# ORDER BY FEE DESC, HISTORY_ID DESC