-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
INNER JOIN PATIENT AS P
    ON A.PT_NO = P.PT_NO
WHERE A.MCDP_CD = "CS" AND
    APNT_YMD like '%2022-04-13%' AND
    A.APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;



